Repository itzg/mc-image-helper, pull requests merged in 2025-02, with the labels that each got.

#516 forge: support CleanroomMC installer
  src/main/java/me/itzg/helpers/forge/ForgeInstaller.java
  src/main/java/me/itzg/helpers/forge/ProvidedInstallerResolver.java
  src/main/java/me/itzg/helpers/forge/VersionPair.java
  src/test/java/me/itzg/helpers/forge/ProvidedInstallerResolverTest.java
  src/test/resources/forge/version-cleanroom.json
  src/test/resources/forge/version-forge-1.12.2.json
  src/test/resources/forge/version-forge-1.20.2.json
Labels: enhancement

#517 fabric: retry download when IO exception
  src/main/java/me/itzg/helpers/fabric/FabricLauncherInstaller.java
  src/main/java/me/itzg/helpers/fabric/FabricMetaClient.java
Labels: enhancement

#523 Add toml-query command
  src/main/java/me/itzg/helpers/McImageHelper.java
  src/main/java/me/itzg/helpers/files/TomlQueryCommand.java
  src/test/java/me/itzg/helpers/files/TomlQueryCommandTest.java
  src/test/resources/velocity.toml
Labels: enhancement

#524 Added README docs for toml-path command
  README.md
  src/main/java/me/itzg/helpers/McImageHelper.java
  src/main/java/me/itzg/helpers/files/TomlPathCommand.java
  src/main/java/me/itzg/helpers/files/YamlPathCommand.java
  src/test/java/me/itzg/helpers/files/TomlPathCommandTest.java
  src/test/java/me/itzg/helpers/files/YamlPathCommandTest.java
Labels: documentation

#526 fabric: skip fabricmc API call when matching version installed
  src/main/java/me/itzg/helpers/fabric/FabricMetaClient.java
  src/test/java/me/itzg/helpers/fabric/FabricLauncherInstallerTest.java
Labels: enhancement

#527 toml-path: match usage of yaml-path
  src/main/java/me/itzg/helpers/files/TomlPathCommand.java
  src/test/java/me/itzg/helpers/files/TomlPathCommandTest.java
Labels: enhancement

#531 Pr/liven/fix placeholder subtitution
  src/main/java/me/itzg/helpers/env/SimplePlaceholders.java
  src/test/java/me/itzg/helpers/properties/SetPropertiesCommandTest.java
  src/test/resources/properties/property-definitions.json
Labels: bug
